---
- hosts: all
  become: yes
  tasks:
          - name: upgrade linux system before reboot
            yum:
                    name: '*'
                    state: latest

          - name: Rebooting the system
            command: reboot

          - name: waiting for 300s for rebooted system to come online
            wait_for:
                    port: 22
                    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
                    search_regex: OpenSSH
                    delay: 10
                    timeout: 300
            vars:
                     ansible_connection: local

          - name: Check 22 port connection by checking uptime
            command: uptime
